[package]
name = "nature_of_code"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
nannou ="0.19.0" 
nannou_egui = "0.19.0"
pretty_env_logger = "0.5.0"
rand = "0.9.0"
rand_distr = "0.5"
